### PR TITLE
Sftp fix

### PR DESCRIPTION
**Pull request by mry-usds**
This PR fixes the STAT related bug in the SSHJ code.

## Changes
- upgraded the SSHJ library (27=>30)
- added .setPreserveAttributes(false)
- added additional info about the InMemoryFile (in particular that it is a file and not a directory)

## Checklist
- [X] Tested locally?
- [X] Added new dependencies?
- [ ] Updated the docs?
- [ ] Added a test?
- [ ] Did you check for sensitive data, and remove any?
- [ ] Are additional approvals needed for this change?
- [ ] Are there potential vulnerabilities or licensing issues with any new dependencies introduced?

## Fixes 

- #issue

## To Be Done

- #issue

### CODE REVIEW

**Comment by RickHawesUSDS** [comment]
Could you explain what was happening to cause the exception and why this fix works?

**Comment by RickHawesUSDS** [comment]
Also, we've disabled retry. Could you enable it in the send function?

**Comment by mry-usds** [comment]
By default, SSHJ moves the file, then attempts to set the permissions on the file to those of the origination.  In our case, this fails as we don't have permissions to set the file attributes.  The line client.getFileTransfer().setPreserveAttributes(false) stop this attempt from happening and uses the mask on the receiving side.

**Review by RickHawesUSDS — APPROVED** [review]
LGTM

**Pull request merged**
