### PR TITLE
Palo Alto Dummy Servers

### PR DESCRIPTION
**Pull request by ronaldheft-usds**
For the Palo Alto test. Not to be merged or deployed.

### CODE REVIEW

**Comment by ronaldheft-usds** [comment]
@jimduff-usds @mauricereeves I believe I have the config changed for the SFTP server. I know I need to change the secrets in my Key Vault, but that should be all that remains.

I'm uncertain on what would be the best way to configure Redux. Looking over our local config, I see I need to add a transport to a receiver. Any recommendations on which to use for the test?

```
transport:
  type: REDOX
  baseUrl: http://13.90.81.254:1080
```

**Comment by jimduff-usds** [comment]
> @jimduff-usds @mauricereeves I believe I have the config changed for the SFTP server. I know I need to change the secrets in my Key Vault, but that should be all that remains.
> 
> I'm uncertain on what would be the best way to configure Redux. Looking over our local config, I see I need to add a transport to a receiver. Any recommendations on which to use for the test?
> 
> ```
> transport:
>   type: REDOX
>   baseUrl: http://13.90.81.254:1080
> ```

@ronaldheft-usds , Redox is used by co-phd, PA* receivers, and the ignore.REDOX receiver.   The last one is the most important, since its part of our smoke test.  Note: PA has two receivers for each county that gets data, one for '-download' and one is REDOX.

**Comment by ronaldheft-usds** [comment]
Thanks @jimduff-usds. I think I have the transport in the correct spot. When you have a moment today, could you verify? I'll then deploy this out to the Palo Alto environment and let them know we're ready for the test.

**Comment by jimduff-usds** [comment]
> Thanks @jimduff-usds. I think I have the transport in the correct spot. When you have a moment today, could you verify? I'll then deploy this out to the Palo Alto environment and let them know we're ready for the test.

@ronaldheft-usds , there's always the chance I've missed something, but it looks good to me.  There are a bunch of other values Redox looks for, eg, `apiKey`, but looking at the code they all appear to have defaults, so I think you are good.

**Review by jimduff-usds — APPROVED** [review]

**Comment by ronaldheft-usds** [comment]
@jimduff-usds Made some additional changes to support running the test suite. I'm running the following command:

```
./prime test --env rheft --run ping,end2end --key <key>
```

I'm seeing the following output from this test suite. My environment should currently be sealed off from the internet via the firewall (they're going to open it up when we run the test), so I'm expecting it to fail, but does this output look correct for that scenario?

```
Running the following tests, POSTing to https://rheft-functionapp.azurewebsites.net/api/reports:
ping                Part of Smoke test          CheckConnections: Is the reports endpoint alive and listening?
end2end             Part of Smoke test          Create Fake data, submit, wait, confirm sent via database lineage data
Starting ping Test: run CheckConnections of https://rheft-functionapp.azurewebsites.net/api/reports
Response to POST: 200
{
  "id" : null,
  "warningCount" : 0,
  "errorCount" : 0,
  "errors" : [ ],
  "warnings" : [ ]
}
Test passed: Ping/CheckConnections
Starting end2end Test: send ignore.ignore-simple-report data to CSV,HL7,HL7_BATCH,REDOX,HL7_NULL,SFTP_LEGACY
11:37:00.630 [main][1] INFO  ca.uhn.hl7v2.util.Home - hapi.home is set to /Users/hyyc/Documents/GitHub/prime-data-hub/prime-router/.
11:37:00.643 [main][1] INFO  ca.uhn.hl7v2.VersionLogger - HAPI version is: 2.3
11:37:00.646 [main][1] INFO  ca.uhn.hl7v2.VersionLogger - Default Structure libraries found for HL7 versions 2.5.1, 
Created datafile ./target/csv_test_files/pdi-covid-19-c0657def-6963-4b2e-a3a9-f383ee4eb116-20210511113700.csv
Response to POST: 400
{
  "id" : null,
  "warningCount" : 0,
  "errorCount" : 1,
  "errors" : [ {
    "scope" : "PARAMETER",
    "id" : "client",
    "details" : "'client:ignore.ignore-simple-report': unknown sender"
  } ],
  "warnings" : [ ]
}
***end2end Test FAILED***:  response code 400
*** Tests FAILED:  end2end ***
```

**Comment by jimduff-usds** [comment]
@ronaldheft-usds , this is weird.    I just did a test run locally, and the client header
  `      ignore.ignore-simple-report   `
worked just fine.

I'm wondering maybe your settings table is empty in your 'rheft' environment??    Try this:
`   ./prime sender get --env rheft --name ignore.ignore-simple-report
`
Note:   _extremely annoyingly_, my memory is that the "--env" used by `./prime sender` is different from the "--env" used by `./prime test`.   So if you added 'rheft' to one list of valid environments, it won't be in the other.

If ignore.ignore-simple-report is missing, I would suspect everything is missing.   You can create all the senders and receivers either by running the settings script inside docker, or by starting report stream and submitting directly to it, as follows:

`./prime multiple-settings set --env rheft --input ./settings/organizations-local.yml
`

Sorry it took so long to respond!!

**Comment by ronaldheft-usds** [comment]
Closing out, as these will never be merged.

**Pull request closed without merging**
