### PR TITLE
Update LIVD table

### PR DESCRIPTION
**Pull request by RickHawesUSDS**
This PR updates the LIVD table to the most recent version. The current version in the Prime is 3 months old. The April 28 update for the LIVD table has new tests, but doesn't update the tests that RS process like the Binax Now, CUE and ID Now. 

## Changes
- Replace table fields in COVID-19 table
- Schema docs
- Release notes

### Testing
- [x] Tested locally?
- [x] Ran `quickTest all`?
- [x] Ran `./prime test` against local Docker ReportStream container?
- [ ] Downloaded a file from `http://localhost:7071/api/download`?
- [ ] Added tests?

### Security
- [ ] Did you check for sensitive data, and remove any? 
- [ ] Does logging contain sensitive data?  
- [ ] Are additional approvals needed for this change?
- [ ] Are there potential vulnerabilities or licensing issues with any new dependencies introduced?

### Process
- [ ] Includes a summary of what a code reviewer should verify?
- [x] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Security
*List potential security threats and mitigations in the PR*

## Fixes
*List GitHub issues this PR fixes*
- #issue

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

### CODE REVIEW

**Review by jimduff-usds — APPROVED** [review]
lgtm

**Comment by jimduff-usds** [comment]
FYI, Tom also created a release notes file, so the two will need merginating.

**Review by carlosfelix2 — CHANGES_REQUESTED** [review]
I got this error when running the quick test.  Could it be a Windows specific issue?
*** ERROR ***: prime did not generate a file that matches [/\]pima.*\.csv

**Comment by carlosfelix2** [comment]
prime end2end test passed

**Comment by carlosfelix2** [comment]
> I got this error when running the quick test. Could it be a Windows specific issue?
> *** ERROR **_: prime did not generate a file that matches [/]pima._.csv

This issue was fixed by @RickHawesUSDS in https://github.com/CDCgov/prime-data-hub/pull/1056/files#diff-6ce4ef0627e6cdc6c5d22baddd3709130b84337ddda62c245f1c6805ccec7466R203 .  I implemented that change locally and the quicktest worked.  Approving with that caveat.

**Review by carlosfelix2 — APPROVED** [review]

**Comment by jimduff-usds** [comment]
@RickHawesUSDS  - there is now a newer LIVD table dated 5/19/21.

**Comment by RickHawesUSDS** [comment]
Added #1166 to track as a follow-up.

**Pull request merged**
