### PR TITLE
Frontend JAMStack skeleton

### PR DESCRIPTION
**Pull request by shanewholloway-usds**
Status: Review & feedback with Matt & Drew on 2021-02-10. Suggested shipping PR as-is and starting the next one.

JAMStack frontend skeleton for PRIME Data Hub.

- USWDS via CDN with integrity on style and script tags
- Uses Eleventy static site generator
- NPM based build tooling
- Mock OpenAPI server

## Changes
- Adds top level `/frontend` artifact
- Adds build dependencies: `node`, `npm`, various npm packages in `package-lock.json`
- Adds development dependencies: `watchexec`

## Checklist
- [x] Tested locally?
- [x] Added new dependencies?
- [x] Updated the docs?
- [x] Did you check for sensitive data, and remove any?

### CODE REVIEW

**Comment by shanewholloway-usds** [comment]
Thanks for the review & feedback. As suggested, moving this PR forward as-is and putting the next pieces in a follow-on PR.

**Review by mry-usds — APPROVED** [review]
Looks good - might want to change the _site => dist but not necessary

**Comment by mry-usds** [comment]
Will need to update the CI/CD build process to include this...

**Comment by shanewholloway-usds** [comment]
@mry-usds I agree on including CI/CD. To come in subsequent PR.

I also thought `_site` was a bit strange, but it is the documented default in Eleventy. Happy to change it if we feel strongly. We can continue in the aforementioned CI/CD integration PR.

**Pull request merged**
